image: maven:3.5.3-jdk-8

build:
  stage: build
  script:
  - 'mvn --batch-mode clean verify'

pages:
  stage: deploy
  script:
  - echo ''
  artifacts:
    paths:
    - target/site/apidocs
  only:
  - master
